# IPython log file

runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
import networkx as nx
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/network_graph.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/random_walk.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/random_walk.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/random_walk.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/random_walk.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/random_walk.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/random_walk.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/random_walk.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/random_walk.py', wdir='C:/Users/bijuangalees/pyweek12')
runfile('C:/Users/bijuangalees/pyweek12/random_walk.py', wdir='C:/Users/bijuangalees/pyweek12')
import networkx as nx
U=nx.Graph()#undirected graph
G=nx.DiGraph()
G.nodes()
#[Out]# NodeView(())
G.nodes()
#[Out]# NodeView(())
import networkx as nx
U=nx.Graph()
G=nx.DiGraph()
G.nodes()
#[Out]# NodeView(())
G.add_nodes_from([i for i in range(5)])
G.nodes()
#[Out]# NodeView((0, 1, 2, 3, 4))
list(G.nodes())
#[Out]# [0, 1, 2, 3, 4]
G.edges()
#[Out]# OutEdgeView([])
G.out_edges()
#[Out]# OutEdgeView([])
G.in_edges()
#[Out]# InEdgeView([])
G.add_edge()
G.add_edge(1,2)
G.edges()
#[Out]# OutEdgeView([(1, 2)])
G.in_edges()
#[Out]# InEdgeView([(1, 2)])
G.out_edges()
#[Out]# OutEdgeView([(1, 2)])
G.out_edges(1)
#[Out]# OutEdgeDataView([(1, 2)])
G.in_edges(1)
#[Out]# InEdgeDataView([])
G.add_edge
#[Out]# <bound method DiGraph.add_edge of <networkx.classes.digraph.DiGraph object at 0x000002AF58F92388>>
G.add_edge(0,3)
G.add_edge(2,3)
G.add_edge(3,2)
G.add_edge(3,4)
G.add_edge(4,1)
list(G.out_edges(2))
#[Out]# [(2, 3)]
list(G.out_edges(3))
#[Out]# [(3, 2), (3, 4)]
list(G.in_edges(3))
#[Out]# [(0, 3), (2, 3)]
runfile('C:/Users/bijuangalees/pyweek12/ipython_log.py', wdir='C:/Users/bijuangalees/pyweek12')
